### ISSUE TITLE
Change "report problem" options to expected problems

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#11]
Job Story: When the user clicks "Report a problem", show them a more accurate list of (expected) problems, so they can more quickly report the problem.

The current "report a problem" dialog is inherited from blok/tracking-protection. We should update the list of problems to the ones we expect under the various privacy protections.

E.g., "I'm not signed-in anymore" could be a problem when we disable 3rd-party cookies?

**Comment by groovecoder** [comment]
@fmarier - can you provide a few problems we anticipate users will experience under the study variations? https://github.com/mozilla/shield-study-privacy/blob/master/lib/study.js#L17-L23

**Comment by fmarier** [comment]
Here are a few possible problems that users might encounter:

- Session-only 3rd-party cookies: none / unknown
- No 3rd-party cookie: impossible to finish payment on some payment gateways, can't log using certain login systems
- Tracking protection: lots of examples in the [breakage meta-bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1101005)
- Referrer trimming: broken images, can't login, broken downloads
- Resist fingerprinting: broken layout, different fonts, flash won't work (maybe [other things too](https://bugzilla.mozilla.org/buglist.cgi?v4=resistfingerprinting&o5=substring&f1=OP&order=Importance&o7=substring&v6=resistfingerprinting&o3=substring&list_id=13541042&short_desc=resistfingerprinting&f8=CP&f0=OP&v3=resistfingerprinting&o6=substring&o2=substring&f9=CP&v7=resistfingerprinting&f4=alias&v5=resistfingerprinting&query_format=advanced&j1=OR&f3=component&o4=substring&f2=product&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&short_desc_type=allwordssubstr&f5=short_desc&f6=status_whiteboard&v2=resistfingerprinting&f7=cf_crash_signature))

**Comment by groovecoder** [comment]
Leaning towards only showing users the breakage options that we think are applicable to their variation.
