### ISSUE TITLE
Create/improve browserAction icon

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#13]
It's currently the same purple shield as blok was, and it doesn't look great - especially on dark theme?

<img width="526" alt="shield-privacy-icon" src="https://cloud.githubusercontent.com/assets/71928/25049099/a0855d0e-2105-11e7-96a6-4224188f458e.png">

**Comment by groovecoder** [comment]
Purple doesn't look good on dark background
Shield icon may be duplicated if privacy.trackingprotection.enabled = true
Something that can catch the eye, but doesn't make users over-submit problems?

@jsavory will get some visual design input on this.

**Comment by jsavory** [comment]
I've talked with Eric and we decided that having a icon that better represents breakage might be a better way to go, so we ended up with a broken page icon that I've attached. Let me know what sizes you will need and what file format and I can make sure you get that.

We also talked about having a subtle indicator for the user when they are clearly having problems, we agreed that the notification red dot might be best. @groovecoder, can we take away that indicator once the user leaves the page? 

![2](https://cloud.githubusercontent.com/assets/6146815/26010628/b1f1e464-371b-11e7-862e-5550b3f15706.png)

**Comment by groovecoder** [comment]
Cool! Per [the `browser_action` manifest description](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action#Choosing_icon_sizes), we can use either:

1. An `.svg` file that will scale automatically to the right size and resolution
2. 3 `.png` files: 16x16-, 32x32-, and 64x64-pixel sizes

Yes, we can remove the browserAction badge if and when the user navigates to a different page.

**Comment by jsavory** [comment]
Eric was able to make an SVG icon, so here it is! Let me know if it works, otherwise I could ask him for the pngs. (apparently it won't allow me to just attach an svg so I zipped it)

[report.svg.zip](https://github.com/mozilla/shield-study-privacy/files/1030343/report.svg.zip)
