### ISSUE TITLE
Give users the ability to opt completely out of the study

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#14]
When a user reports problems/breakage, give them an option to disable the study completely, so they aren't stuck with a completely broken web experience in Firefox.

**Comment by jsavory** [comment]
I've added a third page to the drop down and included the link to drop out of the study there. I've also formatted the other screens so that they look a bit more consistent. Let me know if something doesn't work, or if you have any other suggestions. :)

Link: https://drive.google.com/a/mozilla.com/file/d/0B8kj4Mlm-HJeV1BNendXQ2JSZnc/view?usp=sharing

**Comment by groovecoder** [comment]
Looks good!

In the current implementation, I have 3 panels:

### Report a problem
<img width="362" alt="image" src="https://cloud.githubusercontent.com/assets/71928/26418784/20d2e99e-4083-11e7-850d-f19d33adb50e.png">

### Breakage type
<img width="362" alt="image" src="https://cloud.githubusercontent.com/assets/71928/26418805/2f5edcb6-4083-11e7-9c30-24e730e70386.png">

### Breakage details
<img width="362" alt="image" src="https://cloud.githubusercontent.com/assets/71928/26418826/434ac302-4083-11e7-9e9b-9a79da8a9e08.png">

Should we remove the "Breakage details" panel and replace it with the "Thank you" panel? Or should we keep all 4 panels?

**Comment by jsavory** [comment]
Depends on how helpful the comments section is, I'm leaning towards keeping all 4 panels. Usually these comments can provide some helpful insights, so if you agree I'll make up that screen as well :)

**Comment by groovecoder** [comment]
Yeah I agree the 3rd panel asking for breakage details can be quite helpful.

**Comment by jsavory** [comment]
Updated the screens and actually including the third screen this time ;)

Link: https://drive.google.com/a/mozilla.com/file/d/0B8kj4Mlm-HJeV1BNendXQ2JSZnc/view?usp=sharing

**Comment by groovecoder** [comment]
Should we put the "Disable privacy study" link below the big blue button on *all* of the panels? In case the user is so pissed they don't want to click 3 "next" buttons to get there?
