### ISSUE TITLE
Create orientation tab

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#3]
`lib/feature.js` `orientation` currently only shows a tab with a single message.

We should expand & improve it to explain ...

* The user is part of a study measuring web breakage under increased privacy
* How to use the purple shield icon to report breakage

**Comment by jsavory** [comment]
Here is an initial version of the orientation page, linked below. Let me know if you have any suggestions for changes or if I missed anything, I can easily update and rework it depending on the feedback. Thanks!

https://drive.google.com/a/mozilla.com/file/d/0B8kj4Mlm-HJeeHd5cHZKbkRGckU/view?usp=sharing

**Comment by groovecoder** [comment]
Looks good to me ... @pdolanjski ?

**Comment by groovecoder** [comment]
@jsavory - do you have HTML & CSS assets for this? I've got the plumbing ready, but it may be easier and more accurate to use your assets if you have them.

**Comment by jsavory** [comment]
Unfortunately I don't think I do, I created this document in Sketch. What exactly are you looking for in terms of assets?

**Comment by groovecoder** [comment]
Mainly the font?

**Comment by groovecoder** [comment]
Fixed in https://github.com/mozilla/shield-study-privacy/pull/29.
