### ISSUE TITLE
trackingProtection variation: TP onboarding shows up

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#40]
I'm not sure if this is a bug or not ...

When the study runs in the `trackingProtection` variation, it triggers the onboarding flow for Tracking Protection. While this informs the user about Tracking Protection, it might alter the science of the study?

@gregglind, @fmarier - what do you think? Should we study users who are on-boarded exactly as they would be if we|they enabled tracking protection by default? Or should we study users without any TP onboarding experience?

**Comment by fmarier** [comment]
If we study non-onboarded users, we're essentially studying imaginary users.

Users will always see the onboarding the first time a resource is blocked by TP and we're not proposing to change that in the product, so I think it's fine to test it with the onboarding enabled.

**Comment by groovecoder** [comment]
Good enough for me!
