### ISSUE TITLE
Create AMO consent page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#5]

**Comment by groovecoder** [comment]
@gregglind - is this still required?

**Comment by raymak** [comment]
Assuming, you have the consent text approved by Legal, you have to follow the instructions in https://github.com/gregglind/shield-template to build an AMO addons-server patch. Also create an issue on the addons-server GH page to let them know in advance that you are planning to submit the patch (then the pull request resolves the issue). Addons-server is frozen on Tuesday morning and your page will be published on Thursday. So you need to submit your patch before Tuesday, and as early as possible so they have time to merge it before Tuesday.

**Comment by groovecoder** [comment]
Is there a form/process for getting text approved by Legal?

**Comment by raymak** [comment]
I invited you to the relevant doc. Basically you need to file a legal bug with the text and the exit survey (if your study has one).

**Comment by groovecoder** [comment]
Assigning @wcleung. I also found an example for a current study:

https://addons.mozilla.org/en-US/firefox/shield_study_11

**Comment by groovecoder** [comment]
Note: https://docs.google.com/document/d/1AXtaBJQ7NZ7faUmKXASXtRsDZ6OvMaxadQHRUbHzbg4/edit# is a template doc.

**Comment by groovecoder** [comment]
https://github.com/mozilla/addons-server/pull/5865
