### ISSUE TITLE
Make sure shield telemetry pings adhere to the "v3" schema

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/shield-study-privacy#57]
Per [Bug 1387236](https://bugzilla.mozilla.org/show_bug.cgi?id=1387236), it appears that the shield pings don't match the expected JSON Schema. They should be updated to match the expected format for validation.

The `shield-study` ping schema can be found [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/telemetry/shield-study/shield-study.3.schema.json).

cc @gregglind

**Comment by groovecoder** [comment]
@mreid-moz - this study is scheduled to end soon (28 days from start). And we won't be able to fix the previously submitted pings.

So, is it worth fixing these pings in this study? Or should I just make sure that future study pings adhere to the schema?

**Comment by mreid-moz** [comment]
Ensuring that future studies adhere sounds good to me.
